// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiPlexModelsSubscription
 */
export interface OmbiApiPlexModelsSubscription {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiApiPlexModelsSubscription
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsSubscription
     */
    status?: string;
    /**
     * 
     * @type {object}
     * @memberof OmbiApiPlexModelsSubscription
     */
    plan?: object;
    /**
     * 
     * @type {object}
     * @memberof OmbiApiPlexModelsSubscription
     */
    features?: object;
}


