// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
 */
export interface OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    channel?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    iconEmoji?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    iconUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsNotificationsSlackNotificationSettings
     */
    id?: number;
}


