// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsAuthenticationSettings
 */
export interface OmbiSettingsSettingsModelsAuthenticationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    allowNoPassword?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    requireDigit?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    requiredLength?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    requireLowercase?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    requireNonAlphanumeric?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    requireUppercase?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    enableOAuth?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsAuthenticationSettings
     */
    id?: number;
}


