// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsExternalSonarrSettings
 */
export interface OmbiSettingsSettingsModelsExternalSonarrSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    qualityProfile?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    seasonFolders?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    rootPath?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    qualityProfileAnime?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    rootPathAnime?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    addOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    v3?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    languageProfile?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    ssl?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    subDir?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalSonarrSettings
     */
    id?: number;
}


