// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiPlexModelsOAuthLocation
 */
export interface OmbiApiPlexModelsOAuthLocation {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsOAuthLocation
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsOAuthLocation
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsOAuthLocation
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsOAuthLocation
     */
    subdivisions?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsOAuthLocation
     */
    coordinates?: string;
}


