// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiApiPlexModelsGenre } from './ombi-api-plex-models-genre';
import { OmbiApiPlexModelsMedium } from './ombi-api-plex-models-medium';

/**
 * 
 * @export
 * @interface OmbiApiPlexModelsMetadata
 */
export interface OmbiApiPlexModelsMetadata {
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    ratingKey?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    studio?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    contentRating?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    summary?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    thumb?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    art?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    banner?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    theme?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    leafCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    viewedLeafCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    childCount?: number;
    /**
     * 
     * @type {Array<OmbiApiPlexModelsGenre>}
     * @memberof OmbiApiPlexModelsMetadata
     */
    genre?: Array<OmbiApiPlexModelsGenre>;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    primaryExtraKey?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    parentRatingKey?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentRatingKey?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    guid?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    librarySectionID?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    librarySectionKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    parentKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    parentTitle?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMetadata
     */
    parentIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    parentThumb?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentThumb?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentArt?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    grandparentTheme?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMetadata
     */
    chapterSource?: string;
    /**
     * 
     * @type {Array<OmbiApiPlexModelsMedium>}
     * @memberof OmbiApiPlexModelsMetadata
     */
    media?: Array<OmbiApiPlexModelsMedium>;
}


