// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiStoreEntitiesUserQualityProfiles
 */
export interface OmbiStoreEntitiesUserQualityProfiles {
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    sonarrQualityProfileAnime?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    sonarrRootPathAnime?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    sonarrRootPath?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    sonarrQualityProfile?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    radarrRootPath?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    radarrQualityProfile?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesUserQualityProfiles
     */
    id?: number;
}


