// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsNotificationsPushoverSettings
 */
export interface OmbiSettingsSettingsModelsNotificationsPushoverSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    userToken?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    sound?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
     */
    id?: number;
}


