// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsUpdateSettings
 */
export interface OmbiSettingsSettingsModelsUpdateSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    autoUpdateEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    processName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    useScript?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    scriptLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    windowsServiceName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    windowsService?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    testMode?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsUpdateSettings
     */
    id?: number;
}


