// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiCoreSettingsModelsExternalPlexServers } from './ombi-core-settings-models-external-plex-servers';

/**
 * 
 * @export
 * @interface OmbiCoreSettingsModelsExternalPlexSettings
 */
export interface OmbiCoreSettingsModelsExternalPlexSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiCoreSettingsModelsExternalPlexSettings
     */
    enable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexSettings
     */
    installId?: string;
    /**
     * 
     * @type {Array<OmbiCoreSettingsModelsExternalPlexServers>}
     * @memberof OmbiCoreSettingsModelsExternalPlexSettings
     */
    servers?: Array<OmbiCoreSettingsModelsExternalPlexServers>;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalPlexSettings
     */
    id?: number;
}


