// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiStoreEntitiesOmbiUser } from './ombi-store-entities-ombi-user';
import { OmbiStoreEntitiesRequestsIssues } from './ombi-store-entities-requests-issues';

/**
 * 
 * @export
 * @interface OmbiStoreEntitiesRequestsIssueComments
 */
export interface OmbiStoreEntitiesRequestsIssueComments {
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    issuesId?: number;
    /**
     * 
     * @type {Date}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    date?: Date;
    /**
     * 
     * @type {OmbiStoreEntitiesRequestsIssues}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    issues?: OmbiStoreEntitiesRequestsIssues;
    /**
     * 
     * @type {OmbiStoreEntitiesOmbiUser}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    user?: OmbiStoreEntitiesOmbiUser;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesRequestsIssueComments
     */
    id?: number;
}


