// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsExternalRadarrSettings
 */
export interface OmbiSettingsSettingsModelsExternalRadarrSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    defaultQualityProfile?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    defaultRootPath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    addOnly?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    minimumAvailability?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    ssl?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    subDir?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalRadarrSettings
     */
    id?: number;
}


