// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsCustomizationSettings
 */
export interface OmbiSettingsSettingsModelsCustomizationSettings {
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    applicationName?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    applicationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    customCss?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    enableCustomDonations?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    customDonationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    customDonationMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    logo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    recentlyAddedPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    useCustomPage?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsCustomizationSettings
     */
    id?: number;
}


