// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiStoreEntitiesNotificationTemplates
 */
export interface OmbiStoreEntitiesNotificationTemplates {
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    notificationType?: OmbiStoreEntitiesNotificationTemplatesNotificationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    agent?: OmbiStoreEntitiesNotificationTemplatesAgentEnum;
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesNotificationTemplates
     */
    id?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum OmbiStoreEntitiesNotificationTemplatesNotificationTypeEnum {
    NewRequest = 'NewRequest',
    Issue = 'Issue',
    RequestAvailable = 'RequestAvailable',
    RequestApproved = 'RequestApproved',
    AdminNote = 'AdminNote',
    Test = 'Test',
    RequestDeclined = 'RequestDeclined',
    ItemAddedToFaultQueue = 'ItemAddedToFaultQueue',
    WelcomeEmail = 'WelcomeEmail',
    IssueResolved = 'IssueResolved',
    IssueComment = 'IssueComment',
    Newsletter = 'Newsletter'
}
/**
    * @export
    * @enum {string}
    */
export enum OmbiStoreEntitiesNotificationTemplatesAgentEnum {
    Email = 'Email',
    Discord = 'Discord',
    Pushbullet = 'Pushbullet',
    Pushover = 'Pushover',
    Telegram = 'Telegram',
    Slack = 'Slack',
    Mattermost = 'Mattermost',
    Mobile = 'Mobile'
}



