// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsJobSettings
 */
export interface OmbiSettingsSettingsModelsJobSettings {
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    embyContentSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    sonarrSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    radarrSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    plexContentSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    plexRecentlyAddedSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    couchPotatoSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    automaticUpdater?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    userImporter?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    sickRageSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    refreshMetadata?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    newsletter?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    lidarrArtistSync?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    issuesPurge?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    retryRequests?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    mediaDatabaseRefresh?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsJobSettings
     */
    id?: number;
}


