// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiApiPlexModelsPlexContainer } from './ombi-api-plex-models-plex-container';

/**
 * 
 * @export
 * @interface OmbiModelsExternalPlexLibrariesResponse
 */
export interface OmbiModelsExternalPlexLibrariesResponse {
    /**
     * 
     * @type {OmbiApiPlexModelsPlexContainer}
     * @memberof OmbiModelsExternalPlexLibrariesResponse
     */
    data?: OmbiApiPlexModelsPlexContainer;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiModelsExternalPlexLibrariesResponse
     */
    successful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsExternalPlexLibrariesResponse
     */
    message?: string;
}


