// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiModelsAboutViewModel
 */
export interface OmbiModelsAboutViewModel {
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    branch?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    frameworkDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    osArchitecture?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    osDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    processArchitecture?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsAboutViewModel
     */
    applicationBasePath?: string;
}


