// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiApiSonarrModelsCutoff } from './ombi-api-sonarr-models-cutoff';
import { OmbiApiSonarrModelsItem } from './ombi-api-sonarr-models-item';

/**
 * 
 * @export
 * @interface OmbiApiSonarrModelsSonarrProfile
 */
export interface OmbiApiSonarrModelsSonarrProfile {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiSonarrModelsSonarrProfile
     */
    name?: string;
    /**
     * 
     * @type {OmbiApiSonarrModelsCutoff}
     * @memberof OmbiApiSonarrModelsSonarrProfile
     */
    cutoff?: OmbiApiSonarrModelsCutoff;
    /**
     * 
     * @type {Array<OmbiApiSonarrModelsItem>}
     * @memberof OmbiApiSonarrModelsSonarrProfile
     */
    items?: Array<OmbiApiSonarrModelsItem>;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiSonarrModelsSonarrProfile
     */
    id?: number;
}


