// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiApiPlexModelsOAuthOAuthPin } from './ombi-api-plex-models-oauth-oauth-pin';

/**
 * 
 * @export
 * @interface OmbiModelsPlexOAuthViewModel
 */
export interface OmbiModelsPlexOAuthViewModel {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiModelsPlexOAuthViewModel
     */
    wizard?: boolean;
    /**
     * 
     * @type {OmbiApiPlexModelsOAuthOAuthPin}
     * @memberof OmbiModelsPlexOAuthViewModel
     */
    pin?: OmbiApiPlexModelsOAuthOAuthPin;
}


