// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsUserManagementSettings
 */
export interface OmbiSettingsSettingsModelsUserManagementSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    importPlexAdmin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    importPlexUsers?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    importEmbyUsers?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    movieRequestLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    episodeRequestLimit?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    defaultRoles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    bannedPlexUserIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    bannedEmbyUserIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsUserManagementSettings
     */
    id?: number;
}


