// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiCoreSettingsModelsExternalPlexSelectedLibraries } from './ombi-core-settings-models-external-plex-selected-libraries';

/**
 * 
 * @export
 * @interface OmbiCoreSettingsModelsExternalPlexServers
 */
export interface OmbiCoreSettingsModelsExternalPlexServers {
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    plexAuthToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    machineIdentifier?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    episodeBatchSize?: number;
    /**
     * 
     * @type {Array<OmbiCoreSettingsModelsExternalPlexSelectedLibraries>}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    plexSelectedLibraries?: Array<OmbiCoreSettingsModelsExternalPlexSelectedLibraries>;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    ssl?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    subDir?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalPlexServers
     */
    id?: number;
}


