// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiSettingsSettingsModelsExternalCouchPotatoSettings
 */
export interface OmbiSettingsSettingsModelsExternalCouchPotatoSettings {
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    defaultProfileId?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    ssl?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    subDir?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiSettingsSettingsModelsExternalCouchPotatoSettings
     */
    id?: number;
}


