// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiStoreEntitiesRequestsTvRequests } from './ombi-store-entities-requests-tv-requests';

/**
 * 
 * @export
 * @interface OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsTvRequestsOmbiStoreVersion3000CultureneutralPublicKeyTokennull
 */
export interface OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsTvRequestsOmbiStoreVersion3000CultureneutralPublicKeyTokennull {
    /**
     * 
     * @type {Array<OmbiStoreEntitiesRequestsTvRequests>}
     * @memberof OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsTvRequestsOmbiStoreVersion3000CultureneutralPublicKeyTokennull
     */
    collection?: Array<OmbiStoreEntitiesRequestsTvRequests>;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsTvRequestsOmbiStoreVersion3000CultureneutralPublicKeyTokennull
     */
    total?: number;
}


