// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiPlexModelsServerServerInfo
 */
export interface OmbiApiPlexModelsServerServerInfo {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    port?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    scheme?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    localAddresses?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    machineIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    owned?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    synced?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    sourceTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsServerServerInfo
     */
    home?: string;
}


