// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiPlexModelsMedium
 */
export interface OmbiApiPlexModelsMedium {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    videoResolution?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    bitrate?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    aspectRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiPlexModelsMedium
     */
    audioChannels?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    audioCodec?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    videoCodec?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    container?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    videoFrameRate?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    audioProfile?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsMedium
     */
    videoProfile?: string;
}


