// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiModelsFailedRequestViewModel
 */
export interface OmbiModelsFailedRequestViewModel {
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    failedId?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    releaseYear?: Date;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    requestId?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    type?: OmbiModelsFailedRequestViewModelTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    dts?: Date;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    error?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsFailedRequestViewModel
     */
    retryCount?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum OmbiModelsFailedRequestViewModelTypeEnum {
    TvShow = 'TvShow',
    Movie = 'Movie',
    Album = 'Album'
}



