// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiStoreEntitiesOmbiUser } from './ombi-store-entities-ombi-user';

/**
 * 
 * @export
 * @interface OmbiCoreEngineUserStatsSummary
 */
export interface OmbiCoreEngineUserStatsSummary {
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    totalRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    totalMovieRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    totalTvRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    totalIssues?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    completedRequestsMovies?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    completedRequestsTv?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    completedRequests?: number;
    /**
     * 
     * @type {OmbiStoreEntitiesOmbiUser}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    mostRequestedUserMovie?: OmbiStoreEntitiesOmbiUser;
    /**
     * 
     * @type {OmbiStoreEntitiesOmbiUser}
     * @memberof OmbiCoreEngineUserStatsSummary
     */
    mostRequestedUserTv?: OmbiStoreEntitiesOmbiUser;
}


