// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiStoreEntitiesOmbiUser } from './ombi-store-entities-ombi-user';

/**
 * 
 * @export
 * @interface OmbiStoreEntitiesNotificationUserId
 */
export interface OmbiStoreEntitiesNotificationUserId {
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationUserId
     */
    playerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiStoreEntitiesNotificationUserId
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof OmbiStoreEntitiesNotificationUserId
     */
    addedAt?: Date;
    /**
     * 
     * @type {OmbiStoreEntitiesOmbiUser}
     * @memberof OmbiStoreEntitiesNotificationUserId
     */
    user?: OmbiStoreEntitiesOmbiUser;
    /**
     * 
     * @type {number}
     * @memberof OmbiStoreEntitiesNotificationUserId
     */
    id?: number;
}


