// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiLidarrModelsLidarrRootFolder
 */
export interface OmbiApiLidarrModelsLidarrRootFolder {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiLidarrModelsLidarrRootFolder
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiLidarrModelsLidarrRootFolder
     */
    freeSpace?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof OmbiApiLidarrModelsLidarrRootFolder
     */
    unmappedFolders?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiLidarrModelsLidarrRootFolder
     */
    id?: number;
}


