// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiPlexModelsSectionLite
 */
export interface OmbiApiPlexModelsSectionLite {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsSectionLite
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsSectionLite
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsSectionLite
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiPlexModelsSectionLite
     */
    title?: string;
}


