// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiCoreModelsRequestQuotaCountModel } from './ombi-core-models-request-quota-count-model';
import { OmbiCoreModelsUIClaimCheckboxes } from './ombi-core-models-uiclaim-checkboxes';
import { OmbiStoreEntitiesUserQualityProfiles } from './ombi-store-entities-user-quality-profiles';

/**
 * 
 * @export
 * @interface OmbiModelsIdentityUpdateLocalUserModel
 */
export interface OmbiModelsIdentityUpdateLocalUserModel {
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    currentPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    confirmNewPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    alias?: string;
    /**
     * 
     * @type {Array<OmbiCoreModelsUIClaimCheckboxes>}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    claims?: Array<OmbiCoreModelsUIClaimCheckboxes>;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    emailAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    password?: string;
    /**
     * 
     * @type {Date}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    lastLoggedIn?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    hasLoggedIn?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    userType?: OmbiModelsIdentityUpdateLocalUserModelUserTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    movieRequestLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    episodeRequestLimit?: number;
    /**
     * 
     * @type {OmbiCoreModelsRequestQuotaCountModel}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    episodeRequestQuota?: OmbiCoreModelsRequestQuotaCountModel;
    /**
     * 
     * @type {OmbiCoreModelsRequestQuotaCountModel}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    movieRequestQuota?: OmbiCoreModelsRequestQuotaCountModel;
    /**
     * 
     * @type {OmbiCoreModelsRequestQuotaCountModel}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    musicRequestQuota?: OmbiCoreModelsRequestQuotaCountModel;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    musicRequestLimit?: number;
    /**
     * 
     * @type {OmbiStoreEntitiesUserQualityProfiles}
     * @memberof OmbiModelsIdentityUpdateLocalUserModel
     */
    userQualityProfiles?: OmbiStoreEntitiesUserQualityProfiles;
}

/**
    * @export
    * @enum {string}
    */
export enum OmbiModelsIdentityUpdateLocalUserModelUserTypeEnum {
    LocalUser = 'LocalUser',
    PlexUser = 'PlexUser',
    EmbyUser = 'EmbyUser'
}



