// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiApiSonarrModelsV3Cutoff } from './ombi-api-sonarr-models-v3-cutoff';
import { OmbiApiSonarrModelsV3Languages } from './ombi-api-sonarr-models-v3-languages';

/**
 * 
 * @export
 * @interface OmbiApiSonarrModelsV3LanguageProfiles
 */
export interface OmbiApiSonarrModelsV3LanguageProfiles {
    /**
     * 
     * @type {string}
     * @memberof OmbiApiSonarrModelsV3LanguageProfiles
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiApiSonarrModelsV3LanguageProfiles
     */
    upgradeAllowed?: boolean;
    /**
     * 
     * @type {OmbiApiSonarrModelsV3Cutoff}
     * @memberof OmbiApiSonarrModelsV3LanguageProfiles
     */
    cutoff?: OmbiApiSonarrModelsV3Cutoff;
    /**
     * 
     * @type {Array<OmbiApiSonarrModelsV3Languages>}
     * @memberof OmbiApiSonarrModelsV3LanguageProfiles
     */
    languages?: Array<OmbiApiSonarrModelsV3Languages>;
    /**
     * 
     * @type {number}
     * @memberof OmbiApiSonarrModelsV3LanguageProfiles
     */
    id?: number;
}


