// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiModelsUiLoggingModel
 */
export interface OmbiModelsUiLoggingModel {
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsUiLoggingModel
     */
    level?: OmbiModelsUiLoggingModelLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsUiLoggingModel
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiModelsUiLoggingModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsUiLoggingModel
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsUiLoggingModel
     */
    stackTrace?: string;
    /**
     * 
     * @type {Date}
     * @memberof OmbiModelsUiLoggingModel
     */
    dateTime?: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum OmbiModelsUiLoggingModelLevelEnum {
    Trace = 'Trace',
    Debug = 'Debug',
    Information = 'Information',
    Warning = 'Warning',
    Error = 'Error',
    Critical = 'Critical',
    None = 'None'
}



