// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiCoreSettingsModelsExternalEmbyServers
 */
export interface OmbiCoreSettingsModelsExternalEmbyServers {
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    administratorId?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    serverHostname?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    enableEpisodeSearching?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    ssl?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    subDir?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreSettingsModelsExternalEmbyServers
     */
    id?: number;
}


