// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiApiSonarrModelsV3Cutoff
 */
export interface OmbiApiSonarrModelsV3Cutoff {
    /**
     * 
     * @type {number}
     * @memberof OmbiApiSonarrModelsV3Cutoff
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OmbiApiSonarrModelsV3Cutoff
     */
    name?: string;
}


