// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OmbiModelsExternalPlexUserViewModel
 */
export interface OmbiModelsExternalPlexUserViewModel {
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsExternalPlexUserViewModel
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiModelsExternalPlexUserViewModel
     */
    machineIdentifier?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof OmbiModelsExternalPlexUserViewModel
     */
    libsSelected?: Array<number>;
}


