// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OmbiStoreEntitiesNotificationTemplates } from './ombi-store-entities-notification-templates';

/**
 * 
 * @export
 * @interface OmbiCoreModelsUIDiscordNotificationsViewModel
 */
export interface OmbiCoreModelsUIDiscordNotificationsViewModel {
    /**
     * 
     * @type {Array<OmbiStoreEntitiesNotificationTemplates>}
     * @memberof OmbiCoreModelsUIDiscordNotificationsViewModel
     */
    notificationTemplates?: Array<OmbiStoreEntitiesNotificationTemplates>;
    /**
     * 
     * @type {boolean}
     * @memberof OmbiCoreModelsUIDiscordNotificationsViewModel
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreModelsUIDiscordNotificationsViewModel
     */
    webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OmbiCoreModelsUIDiscordNotificationsViewModel
     */
    username?: string;
    /**
     * 
     * @type {number}
     * @memberof OmbiCoreModelsUIDiscordNotificationsViewModel
     */
    id?: number;
}


