// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { OmbiCoreSettingsModelsExternalEmbySettings } from '../model';
import { OmbiModelsExternalUsersViewModel } from '../model';
/**
 * EmbyApi - axios parameter creator
 * @export
 */
export const EmbyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Signs into the Emby Api
         * @param {object} [apiKey] 
         * @param {OmbiCoreSettingsModelsExternalEmbySettings} [request] The request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyPost(apiKey?: object, request?: OmbiCoreSettingsModelsExternalEmbySettings, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Emby`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"OmbiCoreSettingsModelsExternalEmbySettings" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(request !== undefined ? request : {}) : (request || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the emby users.
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyUsersGet(apiKey?: object, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Emby/users`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmbyApi - functional programming interface
 * @export
 */
export const EmbyApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Signs into the Emby Api
         * @param {object} [apiKey] 
         * @param {OmbiCoreSettingsModelsExternalEmbySettings} [request] The request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyPost(apiKey?: object, request?: OmbiCoreSettingsModelsExternalEmbySettings, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OmbiCoreSettingsModelsExternalEmbySettings> {
            const localVarAxiosArgs = EmbyApiAxiosParamCreator(configuration).embyPost(apiKey, request, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the emby users.
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyUsersGet(apiKey?: object, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OmbiModelsExternalUsersViewModel>> {
            const localVarAxiosArgs = EmbyApiAxiosParamCreator(configuration).embyUsersGet(apiKey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EmbyApi - factory interface
 * @export
 */
export const EmbyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Signs into the Emby Api
         * @param {object} [apiKey] 
         * @param {OmbiCoreSettingsModelsExternalEmbySettings} [request] The request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyPost(apiKey?: object, request?: OmbiCoreSettingsModelsExternalEmbySettings, options?: any) {
            return EmbyApiFp(configuration).embyPost(apiKey, request, options)(axios, basePath);
        },
        /**
         * 
         * @summary Gets the emby users.
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embyUsersGet(apiKey?: object, options?: any) {
            return EmbyApiFp(configuration).embyUsersGet(apiKey, options)(axios, basePath);
        },
    };
};

/**
 * EmbyApi - object-oriented interface
 * @export
 * @class EmbyApi
 * @extends {BaseAPI}
 */
export class EmbyApi extends BaseAPI {
    /**
     * 
     * @summary Signs into the Emby Api
     * @param {object} [apiKey] 
     * @param {OmbiCoreSettingsModelsExternalEmbySettings} [request] The request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmbyApi
     */
    public embyPost(apiKey?: object, request?: OmbiCoreSettingsModelsExternalEmbySettings, options?: any) {
        return EmbyApiFp(this.configuration).embyPost(apiKey, request, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Gets the emby users.
     * @param {object} [apiKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmbyApi
     */
    public embyUsersGet(apiKey?: object, options?: any) {
        return EmbyApiFp(this.configuration).embyUsersGet(apiKey, options)(this.axios, this.basePath);
    }

}
