// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { OmbiModelsFailedRequestViewModel } from '../model';
/**
 * RequestRetryApi - axios parameter creator
 * @export
 */
export const RequestRetryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} queueId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryByQueueIdDelete(queueId: number, apiKey?: object, options: any = {}): RequestArgs {
            // verify required parameter 'queueId' is not null or undefined
            if (queueId === null || queueId === undefined) {
                throw new RequiredError('queueId','Required parameter queueId was null or undefined when calling requestRetryByQueueIdDelete.');
            }
            const localVarPath = `/api/v1/RequestRetry/{queueId}`
                .replace(`{${"queueId"}}`, encodeURIComponent(String(queueId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get\'s all the failed requests that are currently in the queue
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryGet(apiKey?: object, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/RequestRetry`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RequestRetryApi - functional programming interface
 * @export
 */
export const RequestRetryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} queueId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryByQueueIdDelete(queueId: number, apiKey?: object, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = RequestRetryApiAxiosParamCreator(configuration).requestRetryByQueueIdDelete(queueId, apiKey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get\'s all the failed requests that are currently in the queue
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryGet(apiKey?: object, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OmbiModelsFailedRequestViewModel>> {
            const localVarAxiosArgs = RequestRetryApiAxiosParamCreator(configuration).requestRetryGet(apiKey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RequestRetryApi - factory interface
 * @export
 */
export const RequestRetryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} queueId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryByQueueIdDelete(queueId: number, apiKey?: object, options?: any) {
            return RequestRetryApiFp(configuration).requestRetryByQueueIdDelete(queueId, apiKey, options)(axios, basePath);
        },
        /**
         * 
         * @summary Get\'s all the failed requests that are currently in the queue
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRetryGet(apiKey?: object, options?: any) {
            return RequestRetryApiFp(configuration).requestRetryGet(apiKey, options)(axios, basePath);
        },
    };
};

/**
 * RequestRetryApi - object-oriented interface
 * @export
 * @class RequestRetryApi
 * @extends {BaseAPI}
 */
export class RequestRetryApi extends BaseAPI {
    /**
     * 
     * @param {number} queueId 
     * @param {object} [apiKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestRetryApi
     */
    public requestRetryByQueueIdDelete(queueId: number, apiKey?: object, options?: any) {
        return RequestRetryApiFp(this.configuration).requestRetryByQueueIdDelete(queueId, apiKey, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Get\'s all the failed requests that are currently in the queue
     * @param {object} [apiKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestRetryApi
     */
    public requestRetryGet(apiKey?: object, options?: any) {
        return RequestRetryApiFp(this.configuration).requestRetryGet(apiKey, options)(this.axios, this.basePath);
    }

}
