// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * Ombi Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { OmbiControllersTokenControllerTokenRefresh } from '../model';
import { OmbiModelsExternalPlexTokenAuthentication } from '../model';
import { OmbiModelsUserAuthModel } from '../model';
/**
 * TokenApi - axios parameter creator
 * @export
 */
export const TokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} pinId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenByPinIdGet(pinId: number, apiKey?: object, options: any = {}): RequestArgs {
            // verify required parameter 'pinId' is not null or undefined
            if (pinId === null || pinId === undefined) {
                throw new RequiredError('pinId','Required parameter pinId was null or undefined when calling tokenByPinIdGet.');
            }
            const localVarPath = `/api/v1/Token/{pinId}`
                .replace(`{${"pinId"}}`, encodeURIComponent(String(pinId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {object} [apiKey] 
         * @param {OmbiModelsExternalPlexTokenAuthentication} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPlextokenPost(apiKey?: object, model?: OmbiModelsExternalPlexTokenAuthentication, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Token/plextoken`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"OmbiModelsExternalPlexTokenAuthentication" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(model !== undefined ? model : {}) : (model || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the token.
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Token`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"OmbiModelsUserAuthModel" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(model !== undefined ? model : {}) : (model || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refreshes the token.
         * @param {object} [apiKey] 
         * @param {OmbiControllersTokenControllerTokenRefresh} [token] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRefreshPost(apiKey?: object, token?: OmbiControllersTokenControllerTokenRefresh, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Token/refresh`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"OmbiControllersTokenControllerTokenRefresh" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(token !== undefined ? token : {}) : (token || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRequirePasswordPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options: any = {}): RequestArgs {
            const localVarPath = `/api/v1/Token/requirePassword`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("ApiKey")
                    : configuration.apiKey;
                localVarHeaderParameter["ApiKey"] = localVarApiKeyValue;
            }

            if (apiKey !== undefined && apiKey !== null) {
                localVarHeaderParameter['ApiKey'] = String(apiKey);
            }


                localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"OmbiModelsUserAuthModel" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(model !== undefined ? model : {}) : (model || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokenApi - functional programming interface
 * @export
 */
export const TokenApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} pinId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenByPinIdGet(pinId: number, apiKey?: object, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = TokenApiAxiosParamCreator(configuration).tokenByPinIdGet(pinId, apiKey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {object} [apiKey] 
         * @param {OmbiModelsExternalPlexTokenAuthentication} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPlextokenPost(apiKey?: object, model?: OmbiModelsExternalPlexTokenAuthentication, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = TokenApiAxiosParamCreator(configuration).tokenPlextokenPost(apiKey, model, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the token.
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = TokenApiAxiosParamCreator(configuration).tokenPost(apiKey, model, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Refreshes the token.
         * @param {object} [apiKey] 
         * @param {OmbiControllersTokenControllerTokenRefresh} [token] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRefreshPost(apiKey?: object, token?: OmbiControllersTokenControllerTokenRefresh, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = TokenApiAxiosParamCreator(configuration).tokenRefreshPost(apiKey, token, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRequirePasswordPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean> {
            const localVarAxiosArgs = TokenApiAxiosParamCreator(configuration).tokenRequirePasswordPost(apiKey, model, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TokenApi - factory interface
 * @export
 */
export const TokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} pinId 
         * @param {object} [apiKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenByPinIdGet(pinId: number, apiKey?: object, options?: any) {
            return TokenApiFp(configuration).tokenByPinIdGet(pinId, apiKey, options)(axios, basePath);
        },
        /**
         * 
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {object} [apiKey] 
         * @param {OmbiModelsExternalPlexTokenAuthentication} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPlextokenPost(apiKey?: object, model?: OmbiModelsExternalPlexTokenAuthentication, options?: any) {
            return TokenApiFp(configuration).tokenPlextokenPost(apiKey, model, options)(axios, basePath);
        },
        /**
         * 
         * @summary Gets the token.
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any) {
            return TokenApiFp(configuration).tokenPost(apiKey, model, options)(axios, basePath);
        },
        /**
         * 
         * @summary Refreshes the token.
         * @param {object} [apiKey] 
         * @param {OmbiControllersTokenControllerTokenRefresh} [token] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRefreshPost(apiKey?: object, token?: OmbiControllersTokenControllerTokenRefresh, options?: any) {
            return TokenApiFp(configuration).tokenRefreshPost(apiKey, token, options)(axios, basePath);
        },
        /**
         * 
         * @param {object} [apiKey] 
         * @param {OmbiModelsUserAuthModel} [model] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tokenRequirePasswordPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any) {
            return TokenApiFp(configuration).tokenRequirePasswordPost(apiKey, model, options)(axios, basePath);
        },
    };
};

/**
 * TokenApi - object-oriented interface
 * @export
 * @class TokenApi
 * @extends {BaseAPI}
 */
export class TokenApi extends BaseAPI {
    /**
     * 
     * @param {number} pinId 
     * @param {object} [apiKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public tokenByPinIdGet(pinId: number, apiKey?: object, options?: any) {
        return TokenApiFp(this.configuration).tokenByPinIdGet(pinId, apiKey, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
     * @param {object} [apiKey] 
     * @param {OmbiModelsExternalPlexTokenAuthentication} [model] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public tokenPlextokenPost(apiKey?: object, model?: OmbiModelsExternalPlexTokenAuthentication, options?: any) {
        return TokenApiFp(this.configuration).tokenPlextokenPost(apiKey, model, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Gets the token.
     * @param {object} [apiKey] 
     * @param {OmbiModelsUserAuthModel} [model] The model.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public tokenPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any) {
        return TokenApiFp(this.configuration).tokenPost(apiKey, model, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @summary Refreshes the token.
     * @param {object} [apiKey] 
     * @param {OmbiControllersTokenControllerTokenRefresh} [token] The model.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public tokenRefreshPost(apiKey?: object, token?: OmbiControllersTokenControllerTokenRefresh, options?: any) {
        return TokenApiFp(this.configuration).tokenRefreshPost(apiKey, token, options)(this.axios, this.basePath);
    }

    /**
     * 
     * @param {object} [apiKey] 
     * @param {OmbiModelsUserAuthModel} [model] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public tokenRequirePasswordPost(apiKey?: object, model?: OmbiModelsUserAuthModel, options?: any) {
        return TokenApiFp(this.configuration).tokenRequirePasswordPost(apiKey, model, options)(this.axios, this.basePath);
    }

}
